stages:
  - 🏷️ semantic-release

🚀 new-release:
  stage: 🏷️ semantic-release
  image: docker-registry.ippon.fr/accelerators/00-tools/docker-images/semantic-release:1.0.0
  script:
    - semantic-release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^chore\(release\):/
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
